# Generated by Django 4.0 on 2021-12-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_profile_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.CharField(choices=[('ANESTHESIOLOGIST', 'ANESTHESIOLOGIST'), ('CARDIOLOGISTS', 'CARDIOLOGISTS'), ('DERMATOTLOGIST', 'DERMATOTLOGIST'), ('GASTROENTROLOGIST', 'GASTROENTROLOGIST'), ('HEMATOLOGIST', 'HEMATOLOGIST'), ('INTERNISTS', 'INTERNISTS')], max_length=100, null=True)),
                ('experience', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
