# Generated by Django 4.0 on 2021-12-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
